2023-05-29 15:40:59,951 : INFO : root : Loading config.
2023-05-29 15:41:00,275 : INFO : ConfigProcessor : Config spec file cache created: /var/folders/ft/zbkj41rj5wb6vpt67k4g_t180000gn/T/config_spec.mpf_cache
2023-05-29 15:41:00,276 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2023-05-29 15:41:00,276 : WARNING : ConfigProcessor : Config file in cache changed: /Users/weijtmans/Dropbox/dev/pinball/config/config.yaml
2023-05-29 15:41:00,276 : INFO : ConfigProcessor : Loading config from file /Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/mpfconfig.yaml.
2023-05-29 15:41:00,335 : INFO : ConfigProcessor : Loading config: /Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/mpfconfig.yaml
2023-05-29 15:41:00,335 : INFO : ConfigProcessor : Loading config from file /Users/weijtmans/Dropbox/dev/pinball/config/config.yaml.
2023-05-29 15:41:00,350 : INFO : ConfigProcessor : Loading config: /Users/weijtmans/Dropbox/dev/pinball/config/config.yaml
2023-05-29 15:41:00,354 : INFO : ConfigProcessor : Config file cache created: /var/folders/ft/zbkj41rj5wb6vpt67k4g_t180000gn/T/5990d3b039773aa86c29d89c33f7fe2d.mpf_cache
2023-05-29 15:41:00,392 : INFO : ConfigProcessor : Loading config from cache: /var/folders/ft/zbkj41rj5wb6vpt67k4g_t180000gn/T/e6f181099026fef6d8fced6e7d189039.mpf_cache
2023-05-29 15:41:00,393 : INFO : ConfigProcessor : Loading config from cache: /var/folders/ft/zbkj41rj5wb6vpt67k4g_t180000gn/T/b34aaaef8e306d9776092af8bb9baa5f.mpf_cache
2023-05-29 15:41:00,393 : INFO : Machine : Mission Pinball Framework Core Engine v0.56.1.dev7
2023-05-29 15:41:00,393 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs/2023-05-29-15-40-59-mpf-MBP-van-Elgar.home.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2023-05-29 15:41:00,393 : INFO : Machine : MPF path: /Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf
2023-05-29 15:41:00,393 : INFO : Machine : Machine path: /Users/weijtmans/Dropbox/dev/pinball
2023-05-29 15:41:00,394 : INFO : Machine : Platform: darwin
2023-05-29 15:41:00,394 : INFO : Machine : Python executable location: /Users/weijtmans/opt/anaconda3/bin/python
2023-05-29 15:41:00,394 : INFO : Machine : Python version: 3.8.8 (64-bit)
2023-05-29 15:41:00,399 : INFO : Machine : Initialise MPF.
2023-05-29 15:41:00,450 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2023-05-29 15:41:00,477 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2023-05-29 15:41:00,477 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.56.1.dev7', 'prev_value': None, 'change': True}
2023-05-29 15:41:00,477 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.56.1.dev7, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2023-05-29 15:41:00,477 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.8.8', 'prev_value': None, 'change': True}
2023-05-29 15:41:00,486 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'macOS-10.16-x86_64-i386-64bit', 'prev_value': None, 'change': True}
2023-05-29 15:41:00,486 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Darwin', 'prev_value': None, 'change': True}
2023-05-29 15:41:00,486 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '21.6.0', 'prev_value': None, 'change': True}
2023-05-29 15:41:00,486 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': 'Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64', 'prev_value': None, 'change': True}
2023-05-29 15:41:00,486 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'x86_64', 'prev_value': None, 'change': True}
2023-05-29 15:41:00,487 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2023-05-29 15:41:00,498 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2023-05-29 15:41:00,498 : INFO : SwitchController : Found active switch: ('2', <Platform.SmartVirtual>) <switch.s_trough_1>
2023-05-29 15:41:00,498 : INFO : SwitchController : Found active switch: ('3', <Platform.SmartVirtual>) <switch.s_trough_2>
2023-05-29 15:41:00,498 : INFO : SwitchController : Found active switch: ('4', <Platform.SmartVirtual>) <switch.s_trough_3>
2023-05-29 15:41:00,500 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2023-05-29 15:41:00,501 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2023-05-29 15:41:02,355 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2023-05-29 15:41:02,356 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2023-05-29 15:41:02,356 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished name='Task-36' coro=<BallDevice._initialize_async() done, defined at /Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/devices/ball_device/ball_device.py:195> exception=ConfigFileError('Config validation error: Entry ball_device_counter_ball_switches:ball_device_counter_ball_switches:jam_switch = "s_trough_jam" is not valid. Device "s_trough_jam" not found in "switches:" section in your config.')>
Traceback (most recent call last):
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/devices/ball_device/ball_device.py", line 197, in _initialize_async
    await self.ball_count_handler.initialise()
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/devices/ball_device/ball_count_handler.py", line 92, in initialise
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/devices/ball_device/switch_counter.py", line 27, in __init__
    self.config = self.machine.config_validator.validate_config("ball_device_counter_ball_switches", self.config)
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/config_validator.py", line 205, in _validate_config
    processed_config[k] = self.validate_config_item(
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/config_validator.py", line 244, in validate_config_item
    return self.validate_item(item, validation, validation_failure_info)
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/config_validator.py", line 696, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/config_validator.py", line 407, in _validate_type_machine
    return self.validation_error(item, validation_failure_info,
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/config_validator.py", line 713, in validation_error
    raise ConfigFileError("Config validation error: Entry {} = \"{}\" is not valid. {}".format(
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry ball_device_counter_ball_switches:ball_device_counter_ball_switches:jam_switch = "s_trough_jam" is not valid. Device "s_trough_jam" not found in "switches:" section in your config. Error Code: CFE-ConfigValidator-6 (https://docs.missionpinball.org/en/dev/logs/CFE-ConfigValidator-6.html)
2023-05-29 15:41:02,359 : INFO : ball_device.bd_plunger : BCH: Initial count: 0
2023-05-29 15:41:02,359 : INFO : ball_device.bd_plunger : State: idle
2023-05-29 15:41:02,360 : INFO : Machine : Starting the main run loop.
2023-05-29 15:41:02,365 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2023-05-29 15:41:02,366 : INFO : Machine : Shutting down...
2023-05-29 15:41:02,366 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2023-05-29 15:41:02,368 : INFO : EventManager : Event: ======'init_phase_4'====== Args={}
2023-05-29 15:41:02,369 : ERROR : asyncio : Exception in callback <function Util.raise_exceptions at 0x7fe17b96f700>
handle: <Handle Util.raise_exceptions>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/utility_functions.py", line 767, in raise_exceptions
    future.result()
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/ball_controller.py", line 90, in _add_new_balls_to_playfield
    self.num_balls_known = await self._count_all_balls_in_devices()
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/ball_controller.py", line 129, in _count_all_balls_in_devices
    futures.append(asyncio.ensure_future(device.ball_count_handler.counter.wait_for_count_stable()))
AttributeError: 'NoneType' object has no attribute 'wait_for_count_stable'
2023-05-29 15:41:02,372 : INFO : EventManager : Event: ======'machine_var_audits_events_game_ended'====== Args={'value': 0, 'prev_value': None, 'change': True}
2023-05-29 15:41:02,372 : INFO : EventManager : Event: ======'machine_var_audits_events_game_started'====== Args={'value': 2, 'prev_value': None, 'change': True}
2023-05-29 15:41:02,372 : INFO : EventManager : Event: ======'machine_var_audits_player_score'====== Args={'value': {'average': 0, 'top': [], 'total': 0}, 'prev_value': None, 'change': True}
2023-05-29 15:41:02,372 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_flipper_left'====== Args={'value': 0, 'prev_value': None, 'change': True}
2023-05-29 15:41:02,373 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_flipper_right'====== Args={'value': 0, 'prev_value': None, 'change': True}
2023-05-29 15:41:02,373 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_plunger'====== Args={'value': 5, 'prev_value': None, 'change': True}
2023-05-29 15:41:02,373 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_right_inlane'====== Args={'value': 6, 'prev_value': None, 'change': True}
2023-05-29 15:41:02,373 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_start'====== Args={'value': 10, 'prev_value': None, 'change': True}
2023-05-29 15:41:02,373 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_1'====== Args={'value': 2, 'prev_value': None, 'change': True}
2023-05-29 15:41:02,374 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_2'====== Args={'value': 1, 'prev_value': None, 'change': True}
2023-05-29 15:41:02,374 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_3'====== Args={'value': 1, 'prev_value': None, 'change': True}
2023-05-29 15:41:02,374 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_4'====== Args={'value': 0, 'prev_value': None, 'change': True}
2023-05-29 15:41:02,374 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_5'====== Args={'value': 0, 'prev_value': None, 'change': True}
2023-05-29 15:41:02,374 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_6'====== Args={'value': 0, 'prev_value': None, 'change': True}
2023-05-29 15:41:02,375 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_jam'====== Args={'value': 0, 'prev_value': None, 'change': True}
2023-05-29 15:41:02,375 : INFO : EventManager : Event: ======'init_phase_5'====== Args={}
2023-05-29 15:41:02,376 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished name='Task-1' coro=<MachineController.initialise() done, defined at /Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/machine.py:244> exception=AttributeError("'NoneType' object has no attribute 'config'")>
Traceback (most recent call last):
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/machine.py", line 256, in initialise
    await self._start_platforms()
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/machine.py", line 338, in _start_platforms
    await hardware_platform.start()
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/platforms/smart_virtual.py", line 288, in start
    self._initialise_ball_devices()
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/platforms/smart_virtual.py", line 347, in _initialise_ball_devices
    action = device.ejector.config['eject_coil'].hw_driver.action = AddBallToTargetAction(
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/platforms/smart_virtual.py", line 178, in __init__
    self.ball_switches = device.ball_count_handler.counter.config.get('ball_switches', [])
AttributeError: 'NoneType' object has no attribute 'config'
2023-05-29 15:41:02,378 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/machine.py", line 797, in _run_loop
    raise self._exception['exception']
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/devices/ball_device/ball_device.py", line 197, in _initialize_async
    await self.ball_count_handler.initialise()
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/devices/ball_device/ball_count_handler.py", line 92, in initialise
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/devices/ball_device/switch_counter.py", line 27, in __init__
    self.config = self.machine.config_validator.validate_config("ball_device_counter_ball_switches", self.config)
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/config_validator.py", line 205, in _validate_config
    processed_config[k] = self.validate_config_item(
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/config_validator.py", line 244, in validate_config_item
    return self.validate_item(item, validation, validation_failure_info)
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/config_validator.py", line 696, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/config_validator.py", line 407, in _validate_type_machine
    return self.validation_error(item, validation_failure_info,
  File "/Users/weijtmans/opt/anaconda3/lib/python3.8/site-packages/mpf/core/config_validator.py", line 713, in validation_error
    raise ConfigFileError("Config validation error: Entry {} = \"{}\" is not valid. {}".format(
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry ball_device_counter_ball_switches:ball_device_counter_ball_switches:jam_switch = "s_trough_jam" is not valid. Device "s_trough_jam" not found in "switches:" section in your config. Error Code: CFE-ConfigValidator-6 (https://docs.missionpinball.org/en/dev/logs/CFE-ConfigValidator-6.html)
2023-05-29 15:41:37,604 : INFO : root : MPF run loop ended.
